#!/bin/bash
set -e
source db_env.sh

EXT_LOC="ext_bronze_${CUSTOMER//-/_}"
BRONZE_SCHEMA="${CUSTOMER//-/_}_bronze"
SILVER_SCHEMA="${CUSTOMER//-/_}_silver"
GOLD_SCHEMA="${CUSTOMER//-/_}_gold"

SQL=$(cat <<EOF
CREATE EXTERNAL LOCATION IF NOT EXISTS ${EXT_LOC}
URL '${STORAGE_PATH}'
WITH (STORAGE CREDENTIAL new_db_test);

GRANT READ FILES, WRITE FILES
ON EXTERNAL LOCATION ${EXT_LOC}
TO \`${GROUP_NAME}\`;

CREATE SCHEMA IF NOT EXISTS ${CATALOG_NAME}.${BRONZE_SCHEMA}
MANAGED LOCATION '${STORAGE_PATH}';

CREATE SCHEMA IF NOT EXISTS ${CATALOG_NAME}.${SILVER_SCHEMA};
CREATE SCHEMA IF NOT EXISTS ${CATALOG_NAME}.${GOLD_SCHEMA};

GRANT USE CATALOG ON CATALOG ${CATALOG_NAME}
TO \`${GROUP_NAME}\`;

GRANT USE SCHEMA, SELECT
ON SCHEMA ${CATALOG_NAME}.${BRONZE_SCHEMA}
TO \`${GROUP_NAME}\`;

GRANT USE SCHEMA, SELECT
ON SCHEMA ${CATALOG_NAME}.${SILVER_SCHEMA}
TO \`${GROUP_NAME}\`;

GRANT USE SCHEMA, SELECT
ON SCHEMA ${CATALOG_NAME}.${GOLD_SCHEMA}
TO \`${GROUP_NAME}\`;
EOF
)

echo "🚀 Executing SQL via Databricks REST API"

curl -s -X POST \
  "$DATABRICKS_HOST/api/2.0/sql/statements" \
  -H "Authorization: Bearer $DATABRICKS_ADMIN_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{
    \"statement\": $(jq -Rs <<< \"$SQL\"),
    \"warehouse_id\": \"$DATABRICKS_SQL_WAREHOUSE_ID\"
  }"

echo "✅ Schemas + external location + grants created"
